/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.kaixin001.hero.client.upload.tools.auto;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ListList implements org.apache.thrift.TBase<ListList, ListList._Fields>, java.io.Serializable, Cloneable, Comparable<ListList> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ListList");

  private static final org.apache.thrift.protocol.TField TMP_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("tmpList", org.apache.thrift.protocol.TType.LIST, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ListListStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ListListTupleSchemeFactory());
  }

  public List<List<Integer>> tmpList; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    TMP_LIST((short)1, "tmpList");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // TMP_LIST
          return TMP_LIST;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.TMP_LIST, new org.apache.thrift.meta_data.FieldMetaData("tmpList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
                new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ListList.class, metaDataMap);
  }

  public ListList() {
  }

  public ListList(
    List<List<Integer>> tmpList)
  {
    this();
    this.tmpList = tmpList;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ListList(ListList other) {
    if (other.isSetTmpList()) {
      List<List<Integer>> __this__tmpList = new ArrayList<List<Integer>>(other.tmpList.size());
      for (List<Integer> other_element : other.tmpList) {
        List<Integer> __this__tmpList_copy = new ArrayList<Integer>(other_element);
        __this__tmpList.add(__this__tmpList_copy);
      }
      this.tmpList = __this__tmpList;
    }
  }

  public ListList deepCopy() {
    return new ListList(this);
  }

  @Override
  public void clear() {
    this.tmpList = null;
  }

  public int getTmpListSize() {
    return (this.tmpList == null) ? 0 : this.tmpList.size();
  }

  public java.util.Iterator<List<Integer>> getTmpListIterator() {
    return (this.tmpList == null) ? null : this.tmpList.iterator();
  }

  public void addToTmpList(List<Integer> elem) {
    if (this.tmpList == null) {
      this.tmpList = new ArrayList<List<Integer>>();
    }
    this.tmpList.add(elem);
  }

  public List<List<Integer>> getTmpList() {
    return this.tmpList;
  }

  public ListList setTmpList(List<List<Integer>> tmpList) {
    this.tmpList = tmpList;
    return this;
  }

  public void unsetTmpList() {
    this.tmpList = null;
  }

  /** Returns true if field tmpList is set (has been assigned a value) and false otherwise */
  public boolean isSetTmpList() {
    return this.tmpList != null;
  }

  public void setTmpListIsSet(boolean value) {
    if (!value) {
      this.tmpList = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case TMP_LIST:
      if (value == null) {
        unsetTmpList();
      } else {
        setTmpList((List<List<Integer>>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case TMP_LIST:
      return getTmpList();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case TMP_LIST:
      return isSetTmpList();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ListList)
      return this.equals((ListList)that);
    return false;
  }

  public boolean equals(ListList that) {
    if (that == null)
      return false;

    boolean this_present_tmpList = true && this.isSetTmpList();
    boolean that_present_tmpList = true && that.isSetTmpList();
    if (this_present_tmpList || that_present_tmpList) {
      if (!(this_present_tmpList && that_present_tmpList))
        return false;
      if (!this.tmpList.equals(that.tmpList))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ListList other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetTmpList()).compareTo(other.isSetTmpList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTmpList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.tmpList, other.tmpList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ListList(");
    boolean first = true;

    sb.append("tmpList:");
    if (this.tmpList == null) {
      sb.append("null");
    } else {
      sb.append(this.tmpList);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ListListStandardSchemeFactory implements SchemeFactory {
    public ListListStandardScheme getScheme() {
      return new ListListStandardScheme();
    }
  }

  private static class ListListStandardScheme extends StandardScheme<ListList> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ListList struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // TMP_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list36 = iprot.readListBegin();
                struct.tmpList = new ArrayList<List<Integer>>(_list36.size);
                for (int _i37 = 0; _i37 < _list36.size; ++_i37)
                {
                  List<Integer> _elem38;
                  {
                    org.apache.thrift.protocol.TList _list39 = iprot.readListBegin();
                    _elem38 = new ArrayList<Integer>(_list39.size);
                    for (int _i40 = 0; _i40 < _list39.size; ++_i40)
                    {
                      int _elem41;
                      _elem41 = iprot.readI32();
                      _elem38.add(_elem41);
                    }
                    iprot.readListEnd();
                  }
                  struct.tmpList.add(_elem38);
                }
                iprot.readListEnd();
              }
              struct.setTmpListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ListList struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.tmpList != null) {
        oprot.writeFieldBegin(TMP_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, struct.tmpList.size()));
          for (List<Integer> _iter42 : struct.tmpList)
          {
            {
              oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, _iter42.size()));
              for (int _iter43 : _iter42)
              {
                oprot.writeI32(_iter43);
              }
              oprot.writeListEnd();
            }
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ListListTupleSchemeFactory implements SchemeFactory {
    public ListListTupleScheme getScheme() {
      return new ListListTupleScheme();
    }
  }

  private static class ListListTupleScheme extends TupleScheme<ListList> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ListList struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetTmpList()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetTmpList()) {
        {
          oprot.writeI32(struct.tmpList.size());
          for (List<Integer> _iter44 : struct.tmpList)
          {
            {
              oprot.writeI32(_iter44.size());
              for (int _iter45 : _iter44)
              {
                oprot.writeI32(_iter45);
              }
            }
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ListList struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list46 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.LIST, iprot.readI32());
          struct.tmpList = new ArrayList<List<Integer>>(_list46.size);
          for (int _i47 = 0; _i47 < _list46.size; ++_i47)
          {
            List<Integer> _elem48;
            {
              org.apache.thrift.protocol.TList _list49 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.I32, iprot.readI32());
              _elem48 = new ArrayList<Integer>(_list49.size);
              for (int _i50 = 0; _i50 < _list49.size; ++_i50)
              {
                int _elem51;
                _elem51 = iprot.readI32();
                _elem48.add(_elem51);
              }
            }
            struct.tmpList.add(_elem48);
          }
        }
        struct.setTmpListIsSet(true);
      }
    }
  }

}

