/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ActionGroupConfigTable : TBase
  {
    private Dictionary<int, Config.ActionGroupConfig> _actionGroupMap;

    public Dictionary<int, Config.ActionGroupConfig> ActionGroupMap
    {
      get
      {
        return _actionGroupMap;
      }
      set
      {
        __isset.actionGroupMap = true;
        this._actionGroupMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool actionGroupMap;
    }

    public ActionGroupConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ActionGroupMap = new Dictionary<int, Config.ActionGroupConfig>();
                TMap _map135 = iprot.ReadMapBegin();
                for( int _i136 = 0; _i136 < _map135.Count; ++_i136)
                {
                  int _key137;
                  Config.ActionGroupConfig _val138;
                  _key137 = iprot.ReadI32();
                  _val138 = new Config.ActionGroupConfig();
                  _val138.Read(iprot);
                  ActionGroupMap[_key137] = _val138;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ActionGroupConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ActionGroupMap != null && __isset.actionGroupMap) {
        field.Name = "actionGroupMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ActionGroupMap.Count));
          foreach (int _iter139 in ActionGroupMap.Keys)
          {
            oprot.WriteI32(_iter139);
            ActionGroupMap[_iter139].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ActionGroupConfigTable(");
      sb.Append("ActionGroupMap: ");
      sb.Append(ActionGroupMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
