/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class AeroAttributeConfigTable : TBase
  {
    private Dictionary<string, Config.AeroAttributeConfig> _aeroConfigMap;

    public Dictionary<string, Config.AeroAttributeConfig> AeroConfigMap
    {
      get
      {
        return _aeroConfigMap;
      }
      set
      {
        __isset.aeroConfigMap = true;
        this._aeroConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool aeroConfigMap;
    }

    public AeroAttributeConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Map) {
              {
                AeroConfigMap = new Dictionary<string, Config.AeroAttributeConfig>();
                TMap _map110 = iprot.ReadMapBegin();
                for( int _i111 = 0; _i111 < _map110.Count; ++_i111)
                {
                  string _key112;
                  Config.AeroAttributeConfig _val113;
                  _key112 = iprot.ReadString();
                  _val113 = new Config.AeroAttributeConfig();
                  _val113.Read(iprot);
                  AeroConfigMap[_key112] = _val113;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AeroAttributeConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AeroConfigMap != null && __isset.aeroConfigMap) {
        field.Name = "aeroConfigMap";
        field.Type = TType.Map;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.String, TType.Struct, AeroConfigMap.Count));
          foreach (string _iter114 in AeroConfigMap.Keys)
          {
            oprot.WriteString(_iter114);
            AeroConfigMap[_iter114].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AeroAttributeConfigTable(");
      sb.Append("AeroConfigMap: ");
      sb.Append(AeroConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
