/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class AeroLevelUpConfigTable : TBase
  {
    private Dictionary<int, Config.AeroLevelUpConfig> _aeroLevelUpConfigMap;

    public Dictionary<int, Config.AeroLevelUpConfig> AeroLevelUpConfigMap
    {
      get
      {
        return _aeroLevelUpConfigMap;
      }
      set
      {
        __isset.aeroLevelUpConfigMap = true;
        this._aeroLevelUpConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool aeroLevelUpConfigMap;
    }

    public AeroLevelUpConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                AeroLevelUpConfigMap = new Dictionary<int, Config.AeroLevelUpConfig>();
                TMap _map293 = iprot.ReadMapBegin();
                for( int _i294 = 0; _i294 < _map293.Count; ++_i294)
                {
                  int _key295;
                  Config.AeroLevelUpConfig _val296;
                  _key295 = iprot.ReadI32();
                  _val296 = new Config.AeroLevelUpConfig();
                  _val296.Read(iprot);
                  AeroLevelUpConfigMap[_key295] = _val296;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("AeroLevelUpConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (AeroLevelUpConfigMap != null && __isset.aeroLevelUpConfigMap) {
        field.Name = "aeroLevelUpConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, AeroLevelUpConfigMap.Count));
          foreach (int _iter297 in AeroLevelUpConfigMap.Keys)
          {
            oprot.WriteI32(_iter297);
            AeroLevelUpConfigMap[_iter297].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("AeroLevelUpConfigTable(");
      sb.Append("AeroLevelUpConfigMap: ");
      sb.Append(AeroLevelUpConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
