/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BattleBuffConfigTable : TBase
  {
    private Dictionary<int, Config.BattleBuffConfig> _buffConfigMap;

    public Dictionary<int, Config.BattleBuffConfig> BuffConfigMap
    {
      get
      {
        return _buffConfigMap;
      }
      set
      {
        __isset.buffConfigMap = true;
        this._buffConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool buffConfigMap;
    }

    public BattleBuffConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                BuffConfigMap = new Dictionary<int, Config.BattleBuffConfig>();
                TMap _map43 = iprot.ReadMapBegin();
                for( int _i44 = 0; _i44 < _map43.Count; ++_i44)
                {
                  int _key45;
                  Config.BattleBuffConfig _val46;
                  _key45 = iprot.ReadI32();
                  _val46 = new Config.BattleBuffConfig();
                  _val46.Read(iprot);
                  BuffConfigMap[_key45] = _val46;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BattleBuffConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BuffConfigMap != null && __isset.buffConfigMap) {
        field.Name = "buffConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, BuffConfigMap.Count));
          foreach (int _iter47 in BuffConfigMap.Keys)
          {
            oprot.WriteI32(_iter47);
            BuffConfigMap[_iter47].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BattleBuffConfigTable(");
      sb.Append("BuffConfigMap: ");
      sb.Append(BuffConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
