/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BuffClashConfigTable : TBase
  {
    private Dictionary<sbyte, Dictionary<sbyte, sbyte>> _buffClashConfigMap;

    public Dictionary<sbyte, Dictionary<sbyte, sbyte>> BuffClashConfigMap
    {
      get
      {
        return _buffClashConfigMap;
      }
      set
      {
        __isset.buffClashConfigMap = true;
        this._buffClashConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool buffClashConfigMap;
    }

    public BuffClashConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                BuffClashConfigMap = new Dictionary<sbyte, Dictionary<sbyte, sbyte>>();
                TMap _map48 = iprot.ReadMapBegin();
                for( int _i49 = 0; _i49 < _map48.Count; ++_i49)
                {
                  sbyte _key50;
                  Dictionary<sbyte, sbyte> _val51;
                  _key50 = iprot.ReadByte();
                  {
                    _val51 = new Dictionary<sbyte, sbyte>();
                    TMap _map52 = iprot.ReadMapBegin();
                    for( int _i53 = 0; _i53 < _map52.Count; ++_i53)
                    {
                      sbyte _key54;
                      sbyte _val55;
                      _key54 = iprot.ReadByte();
                      _val55 = iprot.ReadByte();
                      _val51[_key54] = _val55;
                    }
                    iprot.ReadMapEnd();
                  }
                  BuffClashConfigMap[_key50] = _val51;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BuffClashConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (BuffClashConfigMap != null && __isset.buffClashConfigMap) {
        field.Name = "buffClashConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.Byte, TType.Map, BuffClashConfigMap.Count));
          foreach (sbyte _iter56 in BuffClashConfigMap.Keys)
          {
            oprot.WriteByte(_iter56);
            {
              oprot.WriteMapBegin(new TMap(TType.Byte, TType.Byte, BuffClashConfigMap[_iter56].Count));
              foreach (sbyte _iter57 in BuffClashConfigMap[_iter56].Keys)
              {
                oprot.WriteByte(_iter57);
                oprot.WriteByte(BuffClashConfigMap[_iter56][_iter57]);
              }
              oprot.WriteMapEnd();
            }
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BuffClashConfigTable(");
      sb.Append("BuffClashConfigMap: ");
      sb.Append(BuffClashConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
