/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CadPlayerConfigTable : TBase
  {
    private Dictionary<int, Config.CadPlayerConfig> _cadPlayerConfigMap;

    public Dictionary<int, Config.CadPlayerConfig> CadPlayerConfigMap
    {
      get
      {
        return _cadPlayerConfigMap;
      }
      set
      {
        __isset.cadPlayerConfigMap = true;
        this._cadPlayerConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool cadPlayerConfigMap;
    }

    public CadPlayerConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                CadPlayerConfigMap = new Dictionary<int, Config.CadPlayerConfig>();
                TMap _map318 = iprot.ReadMapBegin();
                for( int _i319 = 0; _i319 < _map318.Count; ++_i319)
                {
                  int _key320;
                  Config.CadPlayerConfig _val321;
                  _key320 = iprot.ReadI32();
                  _val321 = new Config.CadPlayerConfig();
                  _val321.Read(iprot);
                  CadPlayerConfigMap[_key320] = _val321;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CadPlayerConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CadPlayerConfigMap != null && __isset.cadPlayerConfigMap) {
        field.Name = "cadPlayerConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, CadPlayerConfigMap.Count));
          foreach (int _iter322 in CadPlayerConfigMap.Keys)
          {
            oprot.WriteI32(_iter322);
            CadPlayerConfigMap[_iter322].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CadPlayerConfigTable(");
      sb.Append("CadPlayerConfigMap: ");
      sb.Append(CadPlayerConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
