/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CharacterExpConfigTable : TBase
  {
    private Dictionary<int, Config.CharacterExpConfig> _characterExpConfigMap;

    public Dictionary<int, Config.CharacterExpConfig> CharacterExpConfigMap
    {
      get
      {
        return _characterExpConfigMap;
      }
      set
      {
        __isset.characterExpConfigMap = true;
        this._characterExpConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool characterExpConfigMap;
    }

    public CharacterExpConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                CharacterExpConfigMap = new Dictionary<int, Config.CharacterExpConfig>();
                TMap _map348 = iprot.ReadMapBegin();
                for( int _i349 = 0; _i349 < _map348.Count; ++_i349)
                {
                  int _key350;
                  Config.CharacterExpConfig _val351;
                  _key350 = iprot.ReadI32();
                  _val351 = new Config.CharacterExpConfig();
                  _val351.Read(iprot);
                  CharacterExpConfigMap[_key350] = _val351;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CharacterExpConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CharacterExpConfigMap != null && __isset.characterExpConfigMap) {
        field.Name = "characterExpConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, CharacterExpConfigMap.Count));
          foreach (int _iter352 in CharacterExpConfigMap.Keys)
          {
            oprot.WriteI32(_iter352);
            CharacterExpConfigMap[_iter352].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CharacterExpConfigTable(");
      sb.Append("CharacterExpConfigMap: ");
      sb.Append(CharacterExpConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
