/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class CounterConfigTable : TBase
  {
    private Dictionary<int, Config.CycleCounterConfig> _cycleCounterConfigMap;

    public Dictionary<int, Config.CycleCounterConfig> CycleCounterConfigMap
    {
      get
      {
        return _cycleCounterConfigMap;
      }
      set
      {
        __isset.cycleCounterConfigMap = true;
        this._cycleCounterConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool cycleCounterConfigMap;
    }

    public CounterConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 2:
            if (field.Type == TType.Map) {
              {
                CycleCounterConfigMap = new Dictionary<int, Config.CycleCounterConfig>();
                TMap _map38 = iprot.ReadMapBegin();
                for( int _i39 = 0; _i39 < _map38.Count; ++_i39)
                {
                  int _key40;
                  Config.CycleCounterConfig _val41;
                  _key40 = iprot.ReadI32();
                  _val41 = new Config.CycleCounterConfig();
                  _val41.Read(iprot);
                  CycleCounterConfigMap[_key40] = _val41;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("CounterConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (CycleCounterConfigMap != null && __isset.cycleCounterConfigMap) {
        field.Name = "cycleCounterConfigMap";
        field.Type = TType.Map;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, CycleCounterConfigMap.Count));
          foreach (int _iter42 in CycleCounterConfigMap.Keys)
          {
            oprot.WriteI32(_iter42);
            CycleCounterConfigMap[_iter42].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("CounterConfigTable(");
      sb.Append("CycleCounterConfigMap: ");
      sb.Append(CycleCounterConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
