/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DiyCharConfigTable : TBase
  {
    private Dictionary<int, Config.DiyCharConfig> _diyCharConfigMap;

    public Dictionary<int, Config.DiyCharConfig> DiyCharConfigMap
    {
      get
      {
        return _diyCharConfigMap;
      }
      set
      {
        __isset.diyCharConfigMap = true;
        this._diyCharConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool diyCharConfigMap;
    }

    public DiyCharConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                DiyCharConfigMap = new Dictionary<int, Config.DiyCharConfig>();
                TMap _map288 = iprot.ReadMapBegin();
                for( int _i289 = 0; _i289 < _map288.Count; ++_i289)
                {
                  int _key290;
                  Config.DiyCharConfig _val291;
                  _key290 = iprot.ReadI32();
                  _val291 = new Config.DiyCharConfig();
                  _val291.Read(iprot);
                  DiyCharConfigMap[_key290] = _val291;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DiyCharConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (DiyCharConfigMap != null && __isset.diyCharConfigMap) {
        field.Name = "diyCharConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, DiyCharConfigMap.Count));
          foreach (int _iter292 in DiyCharConfigMap.Keys)
          {
            oprot.WriteI32(_iter292);
            DiyCharConfigMap[_iter292].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DiyCharConfigTable(");
      sb.Append("DiyCharConfigMap: ");
      sb.Append(DiyCharConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
