/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DiyFaceDataConfigTable : TBase
  {
    private Dictionary<int, Config.DiyFaceDataConfig> _diyFaceDataConfigMap;

    public Dictionary<int, Config.DiyFaceDataConfig> DiyFaceDataConfigMap
    {
      get
      {
        return _diyFaceDataConfigMap;
      }
      set
      {
        __isset.diyFaceDataConfigMap = true;
        this._diyFaceDataConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool diyFaceDataConfigMap;
    }

    public DiyFaceDataConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.Map) {
              {
                DiyFaceDataConfigMap = new Dictionary<int, Config.DiyFaceDataConfig>();
                TMap _map461 = iprot.ReadMapBegin();
                for( int _i462 = 0; _i462 < _map461.Count; ++_i462)
                {
                  int _key463;
                  Config.DiyFaceDataConfig _val464;
                  _key463 = iprot.ReadI32();
                  _val464 = new Config.DiyFaceDataConfig();
                  _val464.Read(iprot);
                  DiyFaceDataConfigMap[_key463] = _val464;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DiyFaceDataConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (DiyFaceDataConfigMap != null && __isset.diyFaceDataConfigMap) {
        field.Name = "diyFaceDataConfigMap";
        field.Type = TType.Map;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, DiyFaceDataConfigMap.Count));
          foreach (int _iter465 in DiyFaceDataConfigMap.Keys)
          {
            oprot.WriteI32(_iter465);
            DiyFaceDataConfigMap[_iter465].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DiyFaceDataConfigTable(");
      sb.Append("DiyFaceDataConfigMap: ");
      sb.Append(DiyFaceDataConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
