/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DropConfigTable : TBase
  {
    private Dictionary<int, Config.DropListConfig> _dropListConfigMap;

    public Dictionary<int, Config.DropListConfig> DropListConfigMap
    {
      get
      {
        return _dropListConfigMap;
      }
      set
      {
        __isset.dropListConfigMap = true;
        this._dropListConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool dropListConfigMap;
    }

    public DropConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                DropListConfigMap = new Dictionary<int, Config.DropListConfig>();
                TMap _map120 = iprot.ReadMapBegin();
                for( int _i121 = 0; _i121 < _map120.Count; ++_i121)
                {
                  int _key122;
                  Config.DropListConfig _val123;
                  _key122 = iprot.ReadI32();
                  _val123 = new Config.DropListConfig();
                  _val123.Read(iprot);
                  DropListConfigMap[_key122] = _val123;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DropConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (DropListConfigMap != null && __isset.dropListConfigMap) {
        field.Name = "dropListConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, DropListConfigMap.Count));
          foreach (int _iter124 in DropListConfigMap.Keys)
          {
            oprot.WriteI32(_iter124);
            DropListConfigMap[_iter124].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DropConfigTable(");
      sb.Append("DropListConfigMap: ");
      sb.Append(DropListConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
