/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class FashionConfigTable : TBase
  {
    private Dictionary<int, Config.FashionConfig> _fashionConfigMap;

    public Dictionary<int, Config.FashionConfig> FashionConfigMap
    {
      get
      {
        return _fashionConfigMap;
      }
      set
      {
        __isset.fashionConfigMap = true;
        this._fashionConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool fashionConfigMap;
    }

    public FashionConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                FashionConfigMap = new Dictionary<int, Config.FashionConfig>();
                TMap _map245 = iprot.ReadMapBegin();
                for( int _i246 = 0; _i246 < _map245.Count; ++_i246)
                {
                  int _key247;
                  Config.FashionConfig _val248;
                  _key247 = iprot.ReadI32();
                  _val248 = new Config.FashionConfig();
                  _val248.Read(iprot);
                  FashionConfigMap[_key247] = _val248;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("FashionConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (FashionConfigMap != null && __isset.fashionConfigMap) {
        field.Name = "fashionConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, FashionConfigMap.Count));
          foreach (int _iter249 in FashionConfigMap.Keys)
          {
            oprot.WriteI32(_iter249);
            FashionConfigMap[_iter249].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("FashionConfigTable(");
      sb.Append("FashionConfigMap: ");
      sb.Append(FashionConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
