/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ItemGeneratorConfigTable : TBase
  {
    private Dictionary<int, Config.ItemGeneratorConfig> _itemGenMap;

    public Dictionary<int, Config.ItemGeneratorConfig> ItemGenMap
    {
      get
      {
        return _itemGenMap;
      }
      set
      {
        __isset.itemGenMap = true;
        this._itemGenMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool itemGenMap;
    }

    public ItemGeneratorConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ItemGenMap = new Dictionary<int, Config.ItemGeneratorConfig>();
                TMap _map195 = iprot.ReadMapBegin();
                for( int _i196 = 0; _i196 < _map195.Count; ++_i196)
                {
                  int _key197;
                  Config.ItemGeneratorConfig _val198;
                  _key197 = iprot.ReadI32();
                  _val198 = new Config.ItemGeneratorConfig();
                  _val198.Read(iprot);
                  ItemGenMap[_key197] = _val198;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ItemGeneratorConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ItemGenMap != null && __isset.itemGenMap) {
        field.Name = "itemGenMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ItemGenMap.Count));
          foreach (int _iter199 in ItemGenMap.Keys)
          {
            oprot.WriteI32(_iter199);
            ItemGenMap[_iter199].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ItemGeneratorConfigTable(");
      sb.Append("ItemGenMap: ");
      sb.Append(ItemGenMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
