/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RoomActionMallConfigTable : TBase
  {
    private Dictionary<int, Config.RoomActionMallConfig> _roomActionMallConfigMap;

    public Dictionary<int, Config.RoomActionMallConfig> RoomActionMallConfigMap
    {
      get
      {
        return _roomActionMallConfigMap;
      }
      set
      {
        __isset.roomActionMallConfigMap = true;
        this._roomActionMallConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool roomActionMallConfigMap;
    }

    public RoomActionMallConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                RoomActionMallConfigMap = new Dictionary<int, Config.RoomActionMallConfig>();
                TMap _map259 = iprot.ReadMapBegin();
                for( int _i260 = 0; _i260 < _map259.Count; ++_i260)
                {
                  int _key261;
                  Config.RoomActionMallConfig _val262;
                  _key261 = iprot.ReadI32();
                  _val262 = new Config.RoomActionMallConfig();
                  _val262.Read(iprot);
                  RoomActionMallConfigMap[_key261] = _val262;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RoomActionMallConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RoomActionMallConfigMap != null && __isset.roomActionMallConfigMap) {
        field.Name = "roomActionMallConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RoomActionMallConfigMap.Count));
          foreach (int _iter263 in RoomActionMallConfigMap.Keys)
          {
            oprot.WriteI32(_iter263);
            RoomActionMallConfigMap[_iter263].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RoomActionMallConfigTable(");
      sb.Append("RoomActionMallConfigMap: ");
      sb.Append(RoomActionMallConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
