/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ShockConfigTable : TBase
  {
    private Dictionary<int, Config.ShockConfig> _shockConfigMap;

    public Dictionary<int, Config.ShockConfig> ShockConfigMap
    {
      get
      {
        return _shockConfigMap;
      }
      set
      {
        __isset.shockConfigMap = true;
        this._shockConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool shockConfigMap;
    }

    public ShockConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                ShockConfigMap = new Dictionary<int, Config.ShockConfig>();
                TMap _map155 = iprot.ReadMapBegin();
                for( int _i156 = 0; _i156 < _map155.Count; ++_i156)
                {
                  int _key157;
                  Config.ShockConfig _val158;
                  _key157 = iprot.ReadI32();
                  _val158 = new Config.ShockConfig();
                  _val158.Read(iprot);
                  ShockConfigMap[_key157] = _val158;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ShockConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (ShockConfigMap != null && __isset.shockConfigMap) {
        field.Name = "shockConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, ShockConfigMap.Count));
          foreach (int _iter159 in ShockConfigMap.Keys)
          {
            oprot.WriteI32(_iter159);
            ShockConfigMap[_iter159].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ShockConfigTable(");
      sb.Append("ShockConfigMap: ");
      sb.Append(ShockConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
