/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class StageLogicPointDescConfigTable : TBase
  {
    private Dictionary<int, Config.StageLogicPointDescConfig> _logicPointMap;

    public Dictionary<int, Config.StageLogicPointDescConfig> LogicPointMap
    {
      get
      {
        return _logicPointMap;
      }
      set
      {
        __isset.logicPointMap = true;
        this._logicPointMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool logicPointMap;
    }

    public StageLogicPointDescConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                LogicPointMap = new Dictionary<int, Config.StageLogicPointDescConfig>();
                TMap _map195 = iprot.ReadMapBegin();
                for( int _i196 = 0; _i196 < _map195.Count; ++_i196)
                {
                  int _key197;
                  Config.StageLogicPointDescConfig _val198;
                  _key197 = iprot.ReadI32();
                  _val198 = new Config.StageLogicPointDescConfig();
                  _val198.Read(iprot);
                  LogicPointMap[_key197] = _val198;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("StageLogicPointDescConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (LogicPointMap != null && __isset.logicPointMap) {
        field.Name = "logicPointMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, LogicPointMap.Count));
          foreach (int _iter199 in LogicPointMap.Keys)
          {
            oprot.WriteI32(_iter199);
            LogicPointMap[_iter199].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("StageLogicPointDescConfigTable(");
      sb.Append("LogicPointMap: ");
      sb.Append(LogicPointMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
