/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ChatChannelConfig : TBase
  {
    private int _id;
    private int _costItemId;
    private int _cdTime;
    private int _cdCount;

    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    public int CostItemId
    {
      get
      {
        return _costItemId;
      }
      set
      {
        __isset.costItemId = true;
        this._costItemId = value;
      }
    }

    public int CdTime
    {
      get
      {
        return _cdTime;
      }
      set
      {
        __isset.cdTime = true;
        this._cdTime = value;
      }
    }

    public int CdCount
    {
      get
      {
        return _cdCount;
      }
      set
      {
        __isset.cdCount = true;
        this._cdCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool costItemId;
      public bool cdTime;
      public bool cdCount;
    }

    public ChatChannelConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              Id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              CostItemId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.I32) {
              CdTime = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              CdCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("ChatChannelConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.id) {
        field.Name = "id";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Id);
        oprot.WriteFieldEnd();
      }
      if (__isset.costItemId) {
        field.Name = "costItemId";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CostItemId);
        oprot.WriteFieldEnd();
      }
      if (__isset.cdTime) {
        field.Name = "cdTime";
        field.Type = TType.I32;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CdTime);
        oprot.WriteFieldEnd();
      }
      if (__isset.cdCount) {
        field.Name = "cdCount";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(CdCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("ChatChannelConfig(");
      sb.Append("Id: ");
      sb.Append(Id);
      sb.Append(",CostItemId: ");
      sb.Append(CostItemId);
      sb.Append(",CdTime: ");
      sb.Append(CdTime);
      sb.Append(",CdCount: ");
      sb.Append(CdCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
