/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class DecorateConfig : TBase
  {
    private int _id;
    private int _nameMessageId;
    private string _icon;
    private int _quality;
    private int _firstType;
    private List<DecorateResourceInfo> _resource;
    private int _descMessageId;
    private int _putonFuncId;
    private int _takeoffFuncId;
    private int _sortId;
    private int _activeLimitId;
    private int _activeCostId;
    private int _displayLimitId;
    private int _displayTipType;
    private int _activeTipType;
    private int _funcDescMessageId;
    private int _activeLimitDescMessageId;

    public int Id
    {
      get
      {
        return _id;
      }
      set
      {
        __isset.id = true;
        this._id = value;
      }
    }

    public int NameMessageId
    {
      get
      {
        return _nameMessageId;
      }
      set
      {
        __isset.nameMessageId = true;
        this._nameMessageId = value;
      }
    }

    public string Icon
    {
      get
      {
        return _icon;
      }
      set
      {
        __isset.icon = true;
        this._icon = value;
      }
    }

    public int Quality
    {
      get
      {
        return _quality;
      }
      set
      {
        __isset.quality = true;
        this._quality = value;
      }
    }

    public int FirstType
    {
      get
      {
        return _firstType;
      }
      set
      {
        __isset.firstType = true;
        this._firstType = value;
      }
    }

    public List<DecorateResourceInfo> Resource
    {
      get
      {
        return _resource;
      }
      set
      {
        __isset.resource = true;
        this._resource = value;
      }
    }

    public int DescMessageId
    {
      get
      {
        return _descMessageId;
      }
      set
      {
        __isset.descMessageId = true;
        this._descMessageId = value;
      }
    }

    public int PutonFuncId
    {
      get
      {
        return _putonFuncId;
      }
      set
      {
        __isset.putonFuncId = true;
        this._putonFuncId = value;
      }
    }

    public int TakeoffFuncId
    {
      get
      {
        return _takeoffFuncId;
      }
      set
      {
        __isset.takeoffFuncId = true;
        this._takeoffFuncId = value;
      }
    }

    public int SortId
    {
      get
      {
        return _sortId;
      }
      set
      {
        __isset.sortId = true;
        this._sortId = value;
      }
    }

    public int ActiveLimitId
    {
      get
      {
        return _activeLimitId;
      }
      set
      {
        __isset.activeLimitId = true;
        this._activeLimitId = value;
      }
    }

    public int ActiveCostId
    {
      get
      {
        return _activeCostId;
      }
      set
      {
        __isset.activeCostId = true;
        this._activeCostId = value;
      }
    }

    public int DisplayLimitId
    {
      get
      {
        return _displayLimitId;
      }
      set
      {
        __isset.displayLimitId = true;
        this._displayLimitId = value;
      }
    }

    public int DisplayTipType
    {
      get
      {
        return _displayTipType;
      }
      set
      {
        __isset.displayTipType = true;
        this._displayTipType = value;
      }
    }

    public int ActiveTipType
    {
      get
      {
        return _activeTipType;
      }
      set
      {
        __isset.activeTipType = true;
        this._activeTipType = value;
      }
    }

    public int FuncDescMessageId
    {
      get
      {
        return _funcDescMessageId;
      }
      set
      {
        __isset.funcDescMessageId = true;
        this._funcDescMessageId = value;
      }
    }

    public int ActiveLimitDescMessageId
    {
      get
      {
        return _activeLimitDescMessageId;
      }
      set
      {
        __isset.activeLimitDescMessageId = true;
        this._activeLimitDescMessageId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool id;
      public bool nameMessageId;
      public bool icon;
      public bool quality;
      public bool firstType;
      public bool resource;
      public bool descMessageId;
      public bool putonFuncId;
      public bool takeoffFuncId;
      public bool sortId;
      public bool activeLimitId;
      public bool activeCostId;
      public bool displayLimitId;
      public bool displayTipType;
      public bool activeTipType;
      public bool funcDescMessageId;
      public bool activeLimitDescMessageId;
    }

    public DecorateConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              Id = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              NameMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.String) {
              Icon = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              Quality = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 50:
            if (field.Type == TType.I32) {
              FirstType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 60:
            if (field.Type == TType.List) {
              {
                Resource = new List<DecorateResourceInfo>();
                TList _list175 = iprot.ReadListBegin();
                for( int _i176 = 0; _i176 < _list175.Count; ++_i176)
                {
                  DecorateResourceInfo _elem177 = new DecorateResourceInfo();
                  _elem177 = new DecorateResourceInfo();
                  _elem177.Read(iprot);
                  Resource.Add(_elem177);
                }
                iprot.ReadListEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 70:
            if (field.Type == TType.I32) {
              DescMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 80:
            if (field.Type == TType.I32) {
              PutonFuncId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 90:
            if (field.Type == TType.I32) {
              TakeoffFuncId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 100:
            if (field.Type == TType.I32) {
              SortId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 110:
            if (field.Type == TType.I32) {
              ActiveLimitId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 111:
            if (field.Type == TType.I32) {
              ActiveCostId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 120:
            if (field.Type == TType.I32) {
              DisplayLimitId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 130:
            if (field.Type == TType.I32) {
              DisplayTipType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 140:
            if (field.Type == TType.I32) {
              ActiveTipType = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 160:
            if (field.Type == TType.I32) {
              FuncDescMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 170:
            if (field.Type == TType.I32) {
              ActiveLimitDescMessageId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("DecorateConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.id) {
        field.Name = "id";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Id);
        oprot.WriteFieldEnd();
      }
      if (__isset.nameMessageId) {
        field.Name = "nameMessageId";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(NameMessageId);
        oprot.WriteFieldEnd();
      }
      if (Icon != null && __isset.icon) {
        field.Name = "icon";
        field.Type = TType.String;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(Icon);
        oprot.WriteFieldEnd();
      }
      if (__isset.quality) {
        field.Name = "quality";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Quality);
        oprot.WriteFieldEnd();
      }
      if (__isset.firstType) {
        field.Name = "firstType";
        field.Type = TType.I32;
        field.ID = 50;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(FirstType);
        oprot.WriteFieldEnd();
      }
      if (Resource != null && __isset.resource) {
        field.Name = "resource";
        field.Type = TType.List;
        field.ID = 60;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteListBegin(new TList(TType.Struct, Resource.Count));
          foreach (DecorateResourceInfo _iter178 in Resource)
          {
            _iter178.Write(oprot);
          }
          oprot.WriteListEnd();
        }
        oprot.WriteFieldEnd();
      }
      if (__isset.descMessageId) {
        field.Name = "descMessageId";
        field.Type = TType.I32;
        field.ID = 70;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DescMessageId);
        oprot.WriteFieldEnd();
      }
      if (__isset.putonFuncId) {
        field.Name = "putonFuncId";
        field.Type = TType.I32;
        field.ID = 80;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(PutonFuncId);
        oprot.WriteFieldEnd();
      }
      if (__isset.takeoffFuncId) {
        field.Name = "takeoffFuncId";
        field.Type = TType.I32;
        field.ID = 90;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TakeoffFuncId);
        oprot.WriteFieldEnd();
      }
      if (__isset.sortId) {
        field.Name = "sortId";
        field.Type = TType.I32;
        field.ID = 100;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SortId);
        oprot.WriteFieldEnd();
      }
      if (__isset.activeLimitId) {
        field.Name = "activeLimitId";
        field.Type = TType.I32;
        field.ID = 110;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ActiveLimitId);
        oprot.WriteFieldEnd();
      }
      if (__isset.activeCostId) {
        field.Name = "activeCostId";
        field.Type = TType.I32;
        field.ID = 111;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ActiveCostId);
        oprot.WriteFieldEnd();
      }
      if (__isset.displayLimitId) {
        field.Name = "displayLimitId";
        field.Type = TType.I32;
        field.ID = 120;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DisplayLimitId);
        oprot.WriteFieldEnd();
      }
      if (__isset.displayTipType) {
        field.Name = "displayTipType";
        field.Type = TType.I32;
        field.ID = 130;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(DisplayTipType);
        oprot.WriteFieldEnd();
      }
      if (__isset.activeTipType) {
        field.Name = "activeTipType";
        field.Type = TType.I32;
        field.ID = 140;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ActiveTipType);
        oprot.WriteFieldEnd();
      }
      if (__isset.funcDescMessageId) {
        field.Name = "funcDescMessageId";
        field.Type = TType.I32;
        field.ID = 160;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(FuncDescMessageId);
        oprot.WriteFieldEnd();
      }
      if (__isset.activeLimitDescMessageId) {
        field.Name = "activeLimitDescMessageId";
        field.Type = TType.I32;
        field.ID = 170;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(ActiveLimitDescMessageId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("DecorateConfig(");
      sb.Append("Id: ");
      sb.Append(Id);
      sb.Append(",NameMessageId: ");
      sb.Append(NameMessageId);
      sb.Append(",Icon: ");
      sb.Append(Icon);
      sb.Append(",Quality: ");
      sb.Append(Quality);
      sb.Append(",FirstType: ");
      sb.Append(FirstType);
      sb.Append(",Resource: ");
      sb.Append(Resource);
      sb.Append(",DescMessageId: ");
      sb.Append(DescMessageId);
      sb.Append(",PutonFuncId: ");
      sb.Append(PutonFuncId);
      sb.Append(",TakeoffFuncId: ");
      sb.Append(TakeoffFuncId);
      sb.Append(",SortId: ");
      sb.Append(SortId);
      sb.Append(",ActiveLimitId: ");
      sb.Append(ActiveLimitId);
      sb.Append(",ActiveCostId: ");
      sb.Append(ActiveCostId);
      sb.Append(",DisplayLimitId: ");
      sb.Append(DisplayLimitId);
      sb.Append(",DisplayTipType: ");
      sb.Append(DisplayTipType);
      sb.Append(",ActiveTipType: ");
      sb.Append(ActiveTipType);
      sb.Append(",FuncDescMessageId: ");
      sb.Append(FuncDescMessageId);
      sb.Append(",ActiveLimitDescMessageId: ");
      sb.Append(ActiveLimitDescMessageId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
