/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class GuildExpConfig : TBase
  {
    private int _level;
    private int _totalExp;
    private int _maxMemberCount;
    private int _maxViceLeaderCount;

    public int Level
    {
      get
      {
        return _level;
      }
      set
      {
        __isset.level = true;
        this._level = value;
      }
    }

    public int TotalExp
    {
      get
      {
        return _totalExp;
      }
      set
      {
        __isset.totalExp = true;
        this._totalExp = value;
      }
    }

    public int MaxMemberCount
    {
      get
      {
        return _maxMemberCount;
      }
      set
      {
        __isset.maxMemberCount = true;
        this._maxMemberCount = value;
      }
    }

    public int MaxViceLeaderCount
    {
      get
      {
        return _maxViceLeaderCount;
      }
      set
      {
        __isset.maxViceLeaderCount = true;
        this._maxViceLeaderCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool level;
      public bool totalExp;
      public bool maxMemberCount;
      public bool maxViceLeaderCount;
    }

    public GuildExpConfig() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 10:
            if (field.Type == TType.I32) {
              Level = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 20:
            if (field.Type == TType.I32) {
              TotalExp = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 30:
            if (field.Type == TType.I32) {
              MaxMemberCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 40:
            if (field.Type == TType.I32) {
              MaxViceLeaderCount = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("GuildExpConfig");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.level) {
        field.Name = "level";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(Level);
        oprot.WriteFieldEnd();
      }
      if (__isset.totalExp) {
        field.Name = "totalExp";
        field.Type = TType.I32;
        field.ID = 20;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(TotalExp);
        oprot.WriteFieldEnd();
      }
      if (__isset.maxMemberCount) {
        field.Name = "maxMemberCount";
        field.Type = TType.I32;
        field.ID = 30;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxMemberCount);
        oprot.WriteFieldEnd();
      }
      if (__isset.maxViceLeaderCount) {
        field.Name = "maxViceLeaderCount";
        field.Type = TType.I32;
        field.ID = 40;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(MaxViceLeaderCount);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("GuildExpConfig(");
      sb.Append("Level: ");
      sb.Append(Level);
      sb.Append(",TotalExp: ");
      sb.Append(TotalExp);
      sb.Append(",MaxMemberCount: ");
      sb.Append(MaxMemberCount);
      sb.Append(",MaxViceLeaderCount: ");
      sb.Append(MaxViceLeaderCount);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
