/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace Config
{
  public enum LogicPointType
  {
    PlayerBornPoint = 0,
    ItemGeneratorPoint = 1,
  }
}
