/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class SystemDecorateTypeSortInfo : TBase
  {
    private string _nodeName;
    private int _sortId;

    public string NodeName
    {
      get
      {
        return _nodeName;
      }
      set
      {
        __isset.nodeName = true;
        this._nodeName = value;
      }
    }

    public int SortId
    {
      get
      {
        return _sortId;
      }
      set
      {
        __isset.sortId = true;
        this._sortId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool nodeName;
      public bool sortId;
    }

    public SystemDecorateTypeSortInfo() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.String) {
              NodeName = iprot.ReadString();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 10:
            if (field.Type == TType.I32) {
              SortId = iprot.ReadI32();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("SystemDecorateTypeSortInfo");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (NodeName != null && __isset.nodeName) {
        field.Name = "nodeName";
        field.Type = TType.String;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteString(NodeName);
        oprot.WriteFieldEnd();
      }
      if (__isset.sortId) {
        field.Name = "sortId";
        field.Type = TType.I32;
        field.ID = 10;
        oprot.WriteFieldBegin(field);
        oprot.WriteI32(SortId);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("SystemDecorateTypeSortInfo(");
      sb.Append("NodeName: ");
      sb.Append(NodeName);
      sb.Append(",SortId: ");
      sb.Append(SortId);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
