/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace Config.Table
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class RatioGameConfigTable : TBase
  {
    private Dictionary<int, Config.RatioGameConfig> _ratioGameConfigMap;

    public Dictionary<int, Config.RatioGameConfig> RatioGameConfigMap
    {
      get
      {
        return _ratioGameConfigMap;
      }
      set
      {
        __isset.ratioGameConfigMap = true;
        this._ratioGameConfigMap = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ratioGameConfigMap;
    }

    public RatioGameConfigTable() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.Map) {
              {
                RatioGameConfigMap = new Dictionary<int, Config.RatioGameConfig>();
                TMap _map74 = iprot.ReadMapBegin();
                for( int _i75 = 0; _i75 < _map74.Count; ++_i75)
                {
                  int _key76;
                  Config.RatioGameConfig _val77;
                  _key76 = iprot.ReadI32();
                  _val77 = new Config.RatioGameConfig();
                  _val77.Read(iprot);
                  RatioGameConfigMap[_key76] = _val77;
                }
                iprot.ReadMapEnd();
              }
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("RatioGameConfigTable");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (RatioGameConfigMap != null && __isset.ratioGameConfigMap) {
        field.Name = "ratioGameConfigMap";
        field.Type = TType.Map;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        {
          oprot.WriteMapBegin(new TMap(TType.I32, TType.Struct, RatioGameConfigMap.Count));
          foreach (int _iter78 in RatioGameConfigMap.Keys)
          {
            oprot.WriteI32(_iter78);
            RatioGameConfigMap[_iter78].Write(oprot);
          }
          oprot.WriteMapEnd();
        }
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("RatioGameConfigTable(");
      sb.Append("RatioGameConfigMap: ");
      sb.Append(RatioGameConfigMap);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
